### ISSUE TITLE
Stand-alone instance of pg-mem

### ISSUE THREAD

**Issue by rkristelijn** [oguimbal/pg-mem#360]
It would be great to be able to spin up pg-mem as a standalone server, exposing the postgres port and having data to perform end-to-end tests, e.g. doing graphql queries to your app, specifically to run in a pipeline.

Now it feels like you still need to integrate pg-mem into your test framework, e.g. jest. It would be great if one could separate it and use start-server-and-test to fire up the app and start testing. 

Before I spend a lot of time figuring how, I would like to understand if such a thing is possible using pg-mem or it is time wasted.

Thanks for the effort already so far and your reply!

**Comment by rkristelijn** [comment]
anyway this is how far I came setting up a stand-alone database server; it doesn't respond ok to a connect command:

https://github.com/rkristelijn/pg-mem-server

**Comment by dmurvihill** [comment]
I think there is [other software](https://www.postgresql.org/) that might be better suited for this use case.

**Comment by rkristelijn** [comment]
@dmurvihill can you elaborate how to spin up a db from within docker (docker in docker) in a pipeline? Thanks!

**Comment by dmurvihill** [comment]
Here's my Compose file. The `db` container starts the db and the `migrate` container runs the migrations.

```yml
  db:
    image: 'postgres:15.3-alpine3.18'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp

  migrate:
    build:
      context: 'my-project'
      target: 'my-migrations'
    entrypoint: "sh -c 'sleep 10 && npm run migration:up && npm run seed'"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PW=postgres
    volumes:
      - './my-project/src:/my-project/src'
    depends_on:
      - db
```
